openapi: 3.0.2
info:
  title: 'Referal_links_project'
  version: ''
paths:
  /api/users/:
    get:
      operationId: Список пользователей
      description: 'Просмотр списка пользователей'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/users/me/:
    get:
      operationId: myProfileUser
      description: 'Личный профиль пользователя'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    post:
      operationId: myProfileUser
      description: 'Примерение инвайт-кода другого пользователя.'
      parameters:
      - name: invite_code
        in: path
        required: true
        description: Инвайт код другого пользователя.
        schema:
          type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '400':
          description: 'Если инвайт-код не валиден, либо такого кода не существут.'
      tags:
      - api
  /api/users/{id}/:
    get:
      operationId: retrieveUser
      description: 'Просмотр информации о конкретном пользователе'
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальный идетификатор пользователя.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: 'Пользователь с указанным id найден'
        '404':
          description: 'Пользователь с указанным id не найден'
          
      tags:
      - api
  /api/send_auth_code:
    post:
      operationId: createSendAuthCode
      description: 'Запрос на получение кода авторизации.'
      parameters:
      - name: phone_number
        in: path
        required: true
        description: Номер телефона.
        schema:
          type: string
      responses:
        '200':
          description: 'ОК. Получаем auth_code'
        '400':
          description: 'Недействительный формат номера телефона.'
      tags:
      - api
  /api/check_phone_code:
    post:
      operationId: createCheckPhoneAuthCode
      description: 'Запрос токена.'
      parameters:
      - name: phone_number
        in: path
        required: true
        description: Номер телефона.
        schema:
          type: string
      - name: auth_code
        in: path
        required: true
        description: Код доступа.
        schema:
          type: string
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Не валидный номер телефона или код.'
      tags:
      - api
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        phone_number:
          type: string
          maxLength: 20
        invite_code:
          type: string
          nullable: true
          maxLength: 6
        activated_invite_code:
          type: string
          nullable: true
          maxLength: 6
        invited_users:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - phone_number
