version: '3.8'
services:

  db_postgres:
    image: postgres:13.0-alpine
    volumes:
      - referal_db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    # image: vitaliiluki/referal_backend
    build: ../referal_links
    restart: always
    volumes:
      - referal_static_value:/app/static/
    depends_on:
      - db_postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../referal_links/docs/:/usr/share/nginx/html/redoc/
      - referal_static_value:/var/html/static/

    depends_on:
      - backend

volumes:
  referal_db_value:
  referal_static_value: